### PR TITLE
In quiet mode filter out contacts without a title

### PR DESCRIPTION
**Pull request by vmiklos**
Those are typically duplicates.

### CODE REVIEW

**Comment by novel** [comment]
Could you please elaborate on this use case? It's not very obvious why quiet mode should filter out that.

**Comment by vmiklos** [comment]
The idea is that one typically don't add explicitly such a contact: if there is no title, probably it was automatically added (Google+, etc), and in quiet mode I only want to see contacts I added explicitly.

Example, before the patch:

```
$ build/goocaa -q Smith
"John Smith" <smith42@gmail.com>
"smith42@gmail.com" <smith42@gmail.com>
```

Example, after the patch:

```
$ build/goocaa -q Smith
"John Smith" <smith42@gmail.com>
```

**Comment by novel** [comment]
Maybe it's deserve its own option (e.g. -t), because it could be not obvious for a user that 'quiet' implies such a feature on its own, what do you think?

**Comment by vmiklos** [comment]
Makes sense, I just proposed a commit that makes that a separate option.

**Comment by vmiklos** [comment]
The above versions avoids the unneeded assignment if `-t` is used. :-)

**Comment by novel** [comment]
Merged, thanks!

I think I'll update usage and README and roll out 0.2 soon (and then goocaa should be fine for a couple of more years :-) ).

**Comment by vmiklos** [comment]
Excellent -- I wanted to ask for a tag to help packaging. :-)

**Comment by novel** [comment]
Sorry for the delay, I'm having a crash when working with the cache that I still have no time to trace :(

**Pull request merged**
